### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by rhodomela** [infiduk/my-flask-app#4]
안녕하세요! flask 개발을 공부하던 중에 훌륭한 소스를 공유해주셔서 감사히 잘 받았습니다. 감사합니다.
그런데 실행을 해보니, 회원가입이나 글목록같은 부분처럼 db가 필요한 부분에서는 에러가 나더라구요.
미리 mysql에 접속해서 테이블 등등을 생성해줘야 사용이 가능한건가요?
app.py 초반에 app.config['MYSQL_DB'] = 'myflaskapp' 이렇게 선언이 되어있는데, myflaskapp 이라는 db를 생성해주면 될지 궁금합니다. (현재 윈도우 cmd창에서 하고있는데, 여기서 바로 mysql 접속해서 하면 될지요..)
그리고 그 안에 필요한 테이블과 파라미터들을 공유 부탁드려도 될까요?
제대로 짜여진 flask 앱을 실행시켜보고 공부하는게 목적인데, 완전 초보다보니 다른분들이 올려주신걸 받아도 실행조차 되질 않아 어려움을 겪던 차에 infiduk님의 my-flask-app이 홈까지는 접근이 되어 간절한 마음으로 글을 남겨봅니다ㅠㅠ 도움 주시면 정말 감사하겠습니다!

**Comment by rhodomela** [comment]
+) app.py 소스 내에 있는 class ArticleForm과 class RegisterForm를 참고하여 cmd창에서 직접 mysql 접속하여 아래와 같이 생성까지 했는데요,
CREATE DATABASE myflaskapp default CHARACTER SET UTF8;
create table articles(title varchar(50) not null, body text not null)
create table register(name varchar(50) not null, username varchar(25) not null, email varchar(25) not null, password varchar not null, confirm varchar not null)
웹에서는 여전히 작동이 안되네요. 
회원가입 클릭 시 : 404 Not Found - The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
글 목록 클릭 시 : MySQLdb._exceptions.OperationalError: (1049, "Unknown database 'myflaskapp'")
혹시 따로 연동을 해주는 방법이 있을까요??

**Comment by 9992** [comment]
위 issue는 아래 내용을 dbinfo.py 라는 파일에 작성하시고, app.py가 서버 메인이시라면 해당 메인 파일에 import 시켜주시면 될 것 같습니다.
``` python
MYSQL_HOST = 'localhost' 
MYSQL_USER = 'DB 계정' 
MYSQL_PASSWORD = 'DB 비밀번호' 
MYSQL_DB = 'myflaskapp' 
MYSQL_CURSORCLASS = 'DictCursor'
```

**Comment by infiduk** [comment]
`app.py` 에서 `app.config` 부분에 `MYSQL_HOST`나 `MYSQL_USER`, `MYSQL_PASSWORD`가 rhodomela님의 mysql 정보와 맞지 않아서 `myflaskapp` 이라는  database가 생성되었음에도 에러가 발생할 수 있을 거 같아요..!!

`register` 테이블에 `confirm` 칼럼은 굳이 필요하지 않아요!!
웹 상에서 사용자가 입력한 비밀번호를 한번 더 체크하는 개념으로 쓰이고 DB에는 들어가지 않기 때문에 지워주셔도 됩니다!

`articles` 테이블에 `author` 칼럼도 필요합니다!

그리고... 제가 한번 확인해보고 다시 답변드릴게요...! 많은 도움을 드리고 싶은데 그러지 못해서 죄송하네요...ㅠㅠ

**Comment by rhodomela** [comment]
앗 답 주신것만으로도 너무 감사합니다..!!! 일단 열심히 이것저것 만져보고는 있는데 여전히 db연동이 안된건지 뭔지 웹에서 접근이 안되네요..
mysql 에 아이디는 root 패스워드는 1234 로 설정되어있구요. 그대로 app.py 파일에
app.config['MYSQL_HOST'] = 'localhost'
app.config['MYSQL_USER'] = 'root'
app.config['MYSQL_PASSWORD'] = '1234'
app.config['MYSQL_DB'] = 'myflaskapp'
app.config['MYSQL_CURSORCLASS'] = 'DictCursor'
요렇게 설정했구요, 위에 쓴것처럼 myflaskapp databases랑 register, articles 테이블은 직접 mysql 접속해서 만들어놓은 상태예요.
python app.py 해서 실행하면 홈,소개,로그인 페이지까지는 뜨는데 회원가입이나 글목록을 눌렀을때 에러가 나구요..
딱히 문제가 없는거같은데 안되니 답답하네요ㅠㅠ

**Comment by rhodomela** [comment]
> 위 issue는 아래 내용을 dbinfo.py 라는 파일에 작성하시고,
> app.py가 서버 메인이시라면 해당 메인 파일에 import 시켜주시면 될 것 같습니다.
> ```python
> MYSQL_HOST = 'localhost' 
> MYSQL_USER = 'DB 계정' 
> MYSQL_PASSWORD = 'DB 비밀번호' 
> MYSQL_DB = 'myflaskapp' 
> MYSQL_CURSORCLASS = 'DictCursor'
> ```

app.py 내에 app.config 요렇게 정의하는 부분들이 있어서 따로 dbinfo.py 파일을 만들지 않았는데, 그래도 필요할까요? 일단 말씀해주신대로 파일을 만들긴 했는데 import dbinfo.py 하니 에러가 나서 import하는 방법부터 찾고있네요..ㅎㅎㅎ 답주신건 정말 감사합니다!

**Comment by rhodomela** [comment]
로그인 시도했을때 패스워드 암호화때문에 오류가 나고 있는데요..
app.py 상단에 from passlib.hash import sha256_crypt 요렇게 되어있는데 혹시 sha256 사용하려면 사전에 뭔가 설치가 필요한가요?
pip install passlib 하긴 했는데, ValueError: not a valid sha256_crypt hash 이런 에러가 뜨고 안되고 있어서요.. 구글링을 해봐도 뾰족한 수가 없고 passlib 설치된 폴더내에는 sha256이 없어서 혹시 따로 설정을 하신게 있나 여쭈어봅니다ㅠㅠ

**Comment by 9992** [comment]
[https://pythonhosted.org/passlib/lib/passlib.hash.sha256_crypt.html](https://pythonhosted.org/passlib/lib/passlib.hash.sha256_crypt.html)
위의 사이트에 들어가시면, 아래 소스와 같은 예제 코드가 나와요.
``` python
from passlib.hash import sha256_crypt

# generate new salt, hash password
hash = sha256_crypt.hash("password")
hash
# '$5$rounds=80000$wnsT7Yr92oJoP28r$cKhJImk5mfuSKV9b3mumNzlbstFUplKtQXXMo4G6Ep5'

# same, but with explict number of rounds
 sha256_crypt.using(rounds=12345).hash("password")
'$5$rounds=12345$q3hvJE5mn5jKRsW.$BbbYTFiaImz9rTy03GGi.Jf9YY5bmxN0LU3p3uI1iUB'

# verify password
sha256_crypt.verify("password", hash)
# True
sha256_crypt.verify("letmein", hash)
# False
```
설치를 진행하셨음에도 불구하고 안되시는 경우에는 path 문제일 수 있습니다. pip 경로나, python3가 환경변수로 잘 등록되어있는지 확인해보시는게 좋을 것 같습니다.
